from .cauchy import cauchy
from .exponencial import exponencial
from .gaussiana import gaussiana
from .gaussiana_dupla import gaussiana_dupla
from .pi_shaped import pi_shaped
from .s_shaped import s_shaped
from .sigmoidal import sigmoidal
from .sino_generalizada import sino_generalizada
from .trapezoidal import trapezoidal
from .triangular import triangular
from .triangular_complementar import triangular_complementar
from .z_shaped import z_shaped